### ISSUE TITLE
Support Continuous Localization for Compendium

### ISSUE THREAD

**Issue by xalagor** [YawLighthouse/UMG-Slate-Compendium#13]
How about supporting Continuous Localization in a project via [GitLicalize](https://gitlocalize.com/), for example? Personally, I would like to translate the Compendium into Russian and update the translation as the original changes. And someone will probably want to translate it into other languages supported in the engine.

**Comment by YawLighthouse** [comment]
Sure thing! I didn't expect anybody wanting to localize the compendium(which is very much appreciated!) I added you to the git localize project for it. Thank you very much!

**Comment by YawLighthouse** [comment]
Please comment and let me know if there is any issues with getting setup

**Comment by xalagor** [comment]
I tried it, everything works. It will take a couple of days when I can translate everything, and then a Pull Request will appear.

**Comment by xalagor** [comment]
The README and FAQ are fully translated as of 0.5.0, but there are a couple of things:
- The language in GitLocalize does not have a moderator selected to check Review Requests and make Pull Requests based on them.
- It is possible that some links will not work. Translators won't be able to change them because GitLocalize parses all formatting and only gives the text for translation. And even if you make an exception for once and fix it by hand, there will be problems with a lot of updates and languages. But if the TOC is referenced via custom anchors instead of GitHub-generated ones, and links to other .md's are relative, everything will probably work for any language without any action by translators or maintainers.

**Comment by YawLighthouse** [comment]
Sweet! Yeah I just double checked and everything looks to be working properly. Thank you so much for helping out and localizing this!! I really do appreciate it and I'm sure the community really does as well! ❤️
